Csv parser
NastiaFasova/spring_boot pull request #3
Opened 2020-07-07 17:34 UTC by NastiaFasova

Implemented CsvFileParser

2020-07-08 10:56 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/model/dto/UserDto.java
> +    public Long getId() {
@NastiaFasova юзай ломбок. Видали всі ці Getters and Setters

2020-07-08 10:56 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/model/dto/UserDto.java
> +    public String toString() {
@NastiaFasova аналогічно як із гетерами. Глянь як працює аннотація @ Data

2020-07-08 10:57 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/model/dto/mapper/UserDtoFromFileMapper.java
> +    public UserDto getUserDtoFromFile(String line) {
По суті в цьому методі ти не працюєш з file, тому назва трохи збиває з пантелику. Можемо перейменувати?

2020-07-08 10:58 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/service/impl/CsvFileParser.java
> +public class CsvFileParser implements FileParser {
тут ти також не працюєш з файлом. Давай перейменуємо цей клас?

2020-07-08 10:59 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/service/impl/CsvFileParser.java
> +            users.add(mapper.getUserDtoFromFile(user));
Я б запропонував використати split(",") тут, а не в самому маппері

2020-07-08 11:00 UTC, boroda4436 commented on src/main/java/mate/academy/boot/bootdemo/service/FileParser.java
> +    List<UserDto> parse(List<String> path);
точно в тебе змінна виконує роль path? Я дивлюся на імплементацію і маю деякі сумніви

2020-07-08 11:01 UTC, boroda4436 requested changes
Плюс в тебе в цьому PR є старі файли з попередній PR.

2020-07-09 13:34 UTC, dmytro-hryhoruk commented on .gitignore
> +.vscode/
let's left only those directories which are related to IntelliJ

2020-07-09 14:28 UTC, dmytro-hryhoruk approved these changes

2020-07-09 14:28 UTC, dmytro-hryhoruk commented on src/main/java/mate/academy/boot/bootdemo/service/FileParser.java
> +public interface FileParser {
let's make this interface more abstract by adding parameter
```suggestion
public interface FileParser<T> {
```

2020-07-09 14:28 UTC, dmytro-hryhoruk commented on src/main/java/mate/academy/boot/bootdemo/service/FileParser.java
> +    List<UserDto> parse(List<String> fileData);
```suggestion
    T parse(List<String> fileData);
```

2020-07-09 14:28 UTC, dmytro-hryhoruk commented on src/main/java/mate/academy/boot/bootdemo/service/impl/CsvLinesParser.java
> +public class CsvLinesParser implements FileParser {
```suggestion
public class CsvLinesParser implements FileParser<List<UserDto>> {
```

2020-07-09 15:03 UTC, merged